version: '3.3'
services:
  web_develop: 
    image: "nginx"
    container_name: pokemon
    volumes:
      - ./:/app  
      - ./conf.d:/etc/nginx/conf.d/
    ports:
      - "8080:80"
volumes:
  pockemon: {} 
